### ISSUE TITLE
Allow customizing the max-reached label for checkbox groups

### ISSUE THREAD

**Issue by illright** [illright/attractions#13]
As of now, it is fixed to `Can only select {} values.`. This could be customizable with a prop to allow for i18n.

**Comment by sallaben** [comment]
This could also apply to autocomplete as you mentioned in another issue.

**Comment by aabounegm** [comment]
@sallaben in the `Autocomplete`, all such text is already customizable through the slots. I understand that it is sometimes easier to have a prop that just changes the text directly, but I believe confusion would arise when unwittingly passing both the prop and the custom slot, with the slot taking precedence and making the prop effectively useless. (I know I suffer from this with Vuetify sometimes). However, I think it can still be discussed if it leads to increased productivity or ease of usage.
