### ISSUE TITLE
Mobile bug: a dropdown should close when navigating to a new page or, in general, when it loses focus

### ISSUE THREAD

**Issue by elimisteve** [illright/attractions#134]

**Comment by elimisteve** [comment]
As mentioned here: https://old.reddit.com/r/sveltejs/comments/ieexhf/attractions_a_new_minimal_ui_components_library/g2n7e0k/

**Comment by aabounegm** [comment]
The cause is related to the same problem outlined in #133. A fix for this has already been started.
