### ISSUE TITLE
Do you have design system sketch file?

### ISSUE THREAD

**Issue by wshen001** [illright/attractions#149]
Hi iLLright,
I really like your work, it's an amazing library for Svelte. I would like to use this library for my work. I'm wondering if there's a sketch file for all the components of "attractions" library that I can use for mockup before starting a real code implementation?

Please advice.

**Comment by illright** [comment]
I'm afraid not :)

This library emerged from a website we were building, and for that we only had Figma designs (which are now outdated and arguably not built in accordance to best practices of Figma). As for Sketch, I've never even worked with it. However, if you'd like to build the design files, you're more than welcome to, and I'd be happy to assist if I can.

**Comment by wshen001** [comment]
Thank you @illright for your quick reply. I hope I can find some time to work on it. 👍
