### ISSUE TITLE
Question About the Installation...

### ISSUE THREAD

**Issue by wshen001** [illright/attractions#154]
Hi @illright  I know it's not a smart question. However, I am a bit struggle to go through the installation process of the attractions library. I start with the official Svelte rollup template code. I followed the installation of the following steps:

`npm install --save-dev attractions`
`npm install --save-dev svelte-preprocess node-sass postcss`

And I add the autoProcessor code to the rollup.config.js:
```
autoPreprocess({
  scss: {
    includePaths: [
      './src/theme',
    ],
  },
})
```

But it doesn't seem working properly when I tried to import a simple button component in App.svelte file.
The Button's style doesn't get applied.

```
<script>
	import { Button } from 'attractions';

	export let name;
</script>

<main>
	<h1>Hello {name}!</h1>
	<p>Visit the <a href="https://svelte.dev/tutorial">Svelte tutorial</a> to learn how to build Svelte apps.</p>

	<Button filled>button</Button>
  <Button outline>button</Button>
  <Button>button</Button>
</main>
```

(Btw, there's no document telling me how to import each component. I look up your GitHub code and finally found a sample import statement.)

Could you shed some light to me for the SCSS configuration?

**Comment by illright** [comment]
Did you create an empty file `_attractions-theme.scss` in the directory that you specified in the `includePaths`?
Also check for any build errors or errors in the browser console

**Comment by wshen001** [comment]
@illright  I created `_attractions-theme.scss` in the directory. Could you give me an example of rollup SCSS configuration? I guess I didn't configure correctly. Here is the whole file of my current configuration:

```
import svelte from 'rollup-plugin-svelte';
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import livereload from 'rollup-plugin-livereload';
import { terser } from 'rollup-plugin-terser';
import autoPreprocess from 'svelte-preprocess';

const production = !process.env.ROLLUP_WATCH;

function serve() {
	let server;
	
	function toExit() {
		if (server) server.kill(0);
	}

	return {
		writeBundle() {
			if (server) return;
			server = require('child_process').spawn('npm', ['run', 'start', '--', '--dev'], {
				stdio: ['ignore', 'inherit', 'inherit'],
				shell: true
			});

			process.on('SIGTERM', toExit);
			process.on('exit', toExit);
		}
	};
}

export default {
	input: 'src/main.js',
	output: {
		sourcemap: true,
		format: 'iife',
		name: 'app',
		file: 'public/build/bundle.js'
	},
	plugins: [
		svelte({
			// enable run-time checks when not in production
			dev: !production,
			// we'll extract any component CSS out into
			// a separate file - better for performance
			css: css => {
				css.write('bundle.css');
			}
		}),
		autoPreprocess({
			scss: {
				includePaths: [
					'./src/theme',
				],
			},
		}),

		// If you have external dependencies installed from
		// npm, you'll most likely need these plugins. In
		// some cases you'll need additional configuration -
		// consult the documentation for details:
		// https://github.com/rollup/plugins/tree/master/packages/commonjs
		resolve({
			browser: true,
			dedupe: ['svelte']
		}),
		commonjs(),

		// In dev mode, call `npm run start` once
		// the bundle has been generated
		!production && serve(),

		// Watch the `public` directory and refresh the
		// browser on changes when not in production
		!production && livereload('public'),

		// If we're building for production (npm run build
		// instead of npm run dev), minify
		production && terser()
	],
	watch: {
		clearScreen: false
	}
};

```

**Comment by illright** [comment]
Oh, I see. You should specify the `autoPreprocess` thing as the value of the `preprocess` property on the `svelte` plugin.

Check the sample Rollup config for Sapper [here](https://www.github.com/illright/attractions/tree/master/docs/rollup.config.js)

**Comment by wshen001** [comment]
@illright  I see!!! Oh, great, it's working:

```
		svelte({
			preprocess: autoPreprocess({
				scss: {
					includePaths: [
						'./src/theme/',
					],
				},
			}),
			// enable run-time checks when not in production
			dev: !production,
			// we'll extract any component CSS out into
			// a separate file - better for performance
			css: css => {
				css.write('bundle.css');
			}
		}),
```

I suggest making it more clear in the documentation.. especially for the new starter of RollUp like me. 😅

**Comment by illright** [comment]
Sure, we will add an example config to the docs in the future. So do we consider this resolved?

**Comment by wshen001** [comment]
thanks, let me close this issue. Thank you for your quick response.
