### ISSUE TITLE
Question about Breadcrumbs and Navigation component?

### ISSUE THREAD

**Issue by wshen001** [illright/attractions#157]
@illright I notice that you have the breadcrumbs component on the doc site but is not available from the library. Same to the navigation bar component; is there a particular reason that not supporting it?

Many thanks for your time.

**Comment by aabounegm** [comment]
These components are not part of the library; they were custom made for the docs and are not designed with reusability/customizability in mind as to include it in the library. If they are really needed, we can look into that.

**Comment by illright** [comment]
If you wanna see these components added, you may propose the desired interface: what props/slots would you like to see, etc. We'll add those components in the future

**Comment by wshen001** [comment]
@aabounegm and @illright I believe both components would be highly useful and practical to use in any web app. Will think about the interface when I have some time.

**Comment by aabounegm** [comment]
I think the Breadcrumbs component is clear. It is like [this component](https://github.com/illright/attractions/blob/a9d98761749c39d382122cdd49043b5a1c4880ba/docs/src/components/docs/breadcrumbs.svelte) in the docs that looks like this:
![image](https://user-images.githubusercontent.com/11016151/130049694-19a38ab1-de08-4884-8b6a-c9efd65d0374.png)

But what about the Navigation Bar component? We do not have such component in our docs, and I do not quite understand what exactly you are referring to. Do you have any imagination for what the Navigation Bar component should look like or what it should do?
