### ISSUE TITLE
Error parsing dates and times in the date-picker and time-picker when values are cleared

### ISSUE THREAD

**Issue by RikuVan** [illright/attractions#170]
Steps to reproduce
1. enter a date or time
2. remove the date or time
3. blur the field

Results in one of the following: 
![Screenshot 2020-12-08 at 10 08 42](https://user-images.githubusercontent.com/7317771/101457014-945f6480-393d-11eb-9271-028eb29d2a65.png)
![Screenshot 2020-12-08 at 10 09 03](https://user-images.githubusercontent.com/7317771/101457018-96292800-393d-11eb-8edb-1f41a5491e76.png)

**Comment by illright** [comment]
@RikuVan thanks for the report! I've fixed the issue, will soon roll out a release with the fix.

**Comment by RikuVan** [comment]
Thanks for fixing that quickly @illright!
