### ISSUE TITLE
Move the components from Innopoints

### ISSUE THREAD

**Issue by illright** [illright/attractions#19]
The following components are to be moved from Innopoints:
- [x] Accordion and AccordionSection
- [x] Autocomplete
- [x] Button
- [x] Card (add an outlined version too)
- [x] CheckboxChipGroup
- [x] CheckboxGroup
- [x] DatePicker
- [x] Dialog
- [x] Dot
- [x] Dropdown
- [x] FileInput
- [x] FormField
- [x] Modal
- [x] Popover
- [x] RadioChipGroup
- [x] RadioGroup
- [x] Snackbar
- [x] StarRating
- [x] Switch
- [x] Tabs
- [x] TextField
- [x] TimePicker
- [x] Chip

**Comment by aabounegm** [comment]
After that, I think it will be ready for the first release on NPM

**Comment by illright** [comment]
Why rush though? We don't have documentation yet anyway for this to be useful to anyone but us. I'd say we get the documentation page up and running and call it a grande 1.0.0

**Comment by aabounegm** [comment]
First release can be 0.1, alpha, ...
It's ok if only we can use it. I believe that will actually help find bugs and areas for improvement before the official stable release
