### ISSUE TITLE
Documentation bug: Navigating directly to component page breaks nav accordion

### ISSUE THREAD

**Issue by sallaben** [illright/attractions#204]
https://illright.github.io/attractions/docs/components/autocomplete/

Try to expand Components section from this or any similar nested page -- clicking does not have an effect on the accordion.

**Comment by aabounegm** [comment]
Cannot reproduce. Can you give more information about your browser? Are there any errors in the console?

**Comment by illright** [comment]
I can reproduce this on Firefox, but only after clearing the site data. A reload fixes the problem. No errors in the console, it seems

**Comment by illright** [comment]
Actually, not always [does the reload fix the problem]. It kinda feels like the JS is simply not loading somehow. A page navigation fixes the problem

**Comment by sallaben** [comment]
ua: Mozilla/5.0 [...] Gecko/20100101 Firefox/84.0

Here is a video. I couldn't diagnose the issue myself -- nothing appears in the console.

https://user-images.githubusercontent.com/7699235/103415133-d51e5800-4b4e-11eb-81af-511473dabfeb.mov

**Comment by aabounegm** [comment]
I think this is a Firefox problem, somehow. I had v81 and it worked fine, but when I updated I got the behavior you are experiencing. I ran a profile using the performance tab in DevTools, and it seems like the appropriate handlers are being called. Further investigation needed, though.

**Comment by aabounegm** [comment]
After the latest release (v3.1.0), I can no longer reproduce this issue (even on the same Firefox v84, Windows 10). It might have been some temporary issue with Sapper or something else, I cannot really figure it out.
@sallaben can you confirm if the issue is fixed?

**Comment by illright** [comment]
Can't reproduce this anymore either. We will consider this resolved for now, feel free to reopen if you encounter this issue again.

**Comment by sallaben** [comment]
Yep thanks guys I also can't reproduce this anymore.
