### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by orefalo** [illright/attractions#255]
First and foremost, thanks for sharing this library. great job.

I see that you have a component for pagination, how would you use it with a table?
  Implicitly, I am also asking for the table component which I couldn't find.

Thank you

**Comment by illright** [comment]
Well, the [`Pagination`](https://illright.github.io/attractions/docs/components/pagination) component exposes a `currentPage` prop which you can read and use to alter the data in the table:
```svelte
<script>
  import { Pagination } from 'attractions';
  import { Table } from 'elsewhere';

  let currentPage = 1;
  const totalPages = 20;
  const itemsPerPage = 10;

  export let tableData;
</script>

<Table data={tableData.slice((currentPage - 1) * itemsPerPage, currentPage * itemsPerPage)} />
<Pagination bind:currentPage pages={totalPages} />
```

We don't provide a Table component yet, though it could be added in the future. We are a little busy with other work at the moment to add it in right now, but we would certainly welcome a PR adding it.

**Comment by aabounegm** [comment]
If you liked the tables in the documentation, you can take a look at the [_docs/static/css/mdsvex_](https://github.com/illright/attractions/tree/4ee46fb07506c7b92d69477d0b1294ea422599b4/docs/static/css/mdsvex) folder, where we keep the SCSS for `table`, `th`, `tr`, and `td`. I am thinking it shouldn't be too much work copying them over to a new component while adding a few SCSS variables and slots here and there, but I am not sure when I will be able to give it a shot. If you come up with something and would like to add it to the library, we would be happy to merge it.

**Comment by orefalo** [comment]
Thank you so much. It's enough for my current use case
