### ISSUE TITLE
Overriding sass variables only with rollup?

### ISSUE THREAD

**Issue by jcschmidig** [illright/attractions#259]
Just to make sure: you do use `svelte.config.js` in `rollup.config.js`, right? :)
_Originally posted by @illright in https://github.com/illright/attractions/issues/240#issuecomment-773113743_

I have the same problem as described in the above issue, BUT am using webpack.
Does the comment mean that overriding is not working with webpack?

**Comment by aabounegm** [comment]
In the linked issue, the problem was a wrong import style in the documentation for the Rollup config. The comment you quoted is not specific to Rollup, it just happened to be the bundler used by that issue's OP.

If you followed the installation instructions in the docs and it still doesn't work, it would be great if you can share the code with which we can reproduce the issue.
If you are just asking whether it applies and didn't try yet, I encourage you to use the Discussions section in the repo instead :)

**Comment by jcschmidig** [comment]
Sorry for misinterpreting the comment.
I set up a simplified repository to show my problem: [https://github.com/jcschmidig/mfe-svelte-attractions](https://github.com/jcschmidig/mfe-svelte-attractions).
Thanks for having a look!

**Comment by illright** [comment]
Thanks for the MFE. Given my limited expertise with Webpack, I can't offer an elaborate explanation, but I found a fix for the issue.

In your `ci/webpack.config.js`, add the `resolve` section to the config and remove `node_modules` from the exclusion list for `svelte-loader`:

```js
// ...

module.exports = {
  // ...
  // Taken from https://github.com/sveltejs/template-webpack/blob/master/webpack.config.js
  resolve: {
    alias: {
      svelte: path.dirname(require.resolve('svelte/package.json'))
    },
    extensions: ['.mjs', '.js', '.svelte'],
    mainFields: ['svelte', 'browser', 'module', 'main']
  },
  module: {
    rules: [
      {
        test: /\.svelte?$/,
        // exclude: [path.resolve(appPath, 'node_modules')],
        loader: 'svelte-loader',
        options: { ...svelteConfig }
      },
    ],
  },
  // ...
};
```

I've also noticed that your Webpack config differs quite a lot from the one suggested in the [Svelte app template for Webpack](https://github.com/sveltejs/template-webpack), so if this is something you can change, I'd advise you to upgrade to Webpack 5 and make the config more similar to the template one. I just personally found it very useful to let Svelte devs resolve certain configuration issues and just copy from them :)

**Comment by jcschmidig** [comment]
Thanks a lot for your quick and successful fix!
I can't upgrade to webpack 5 currently but will pursue the subject and follow recommendations.
Again, many thanks!
