### ISSUE TITLE
Add slot for FileDropzone to be able to change the wording/language

### ISSUE THREAD

**Issue by gevera** [illright/attractions#261]
Hi. As far as I understand, right now there is no way to change the wording for FileDropzone "drag & drop here or click to upload files" to something like "перетащите сюда или нажмите, чтобы загрузить файлы". I hope it makes sense

Maybe by adding a slot or a special property we could manage the wording. Thanks

`
{#if disabled}
        {textDisabled}
{:else if wrongType}
        {textIncorect}
{:else if dragActive}
        {textDrag}
{:else}
       {textDefault}
{/if}
`

**Comment by illright** [comment]
There is a way to do that, in fact, exactly with slots. `FileDropzone` [exposes a couple of named slots](https://illright.github.io/attractions/docs/components/file-dropzone#slots), the `empty-layer` one is of our interest. It also has two slot props, `wrongType` and `dragActive` to help you make it interactive.

So if you wanted to localize the field to Russian, here's how you'd do it:
```svelte
<script>
  let disabled = false;
</script>

<FileDropzone>
  <svelte:fragment slot="empty-layer" let:wrongType let:dragActive>
    {#if disabled}
      загрузка недоступна
    {:else if wrongType}
      неверный тип файла
    {:else if dragActive}
      отпустите, чтобы загрузить
    {:else}перетащите сюда или нажмите, чтобы загрузить файлы{/if}
  </svelte:fragment>
</FileDropzone>
```

And you can spice it up with a paperclip icon from Feather Icons, as it is [originally done](https://github.com/illright/attractions/blob/main/attractions/file-input/file-dropzone.svelte#L124).

**Comment by gevera** [comment]
You're just awesome. Thanks for the quick reply! Maybe this could be copied to the docs?  I'm sure this will be useful. Спасибо

**Comment by illright** [comment]
Sure, but in the future, when we redesign the docs to create an examples section
