### ISSUE TITLE
Button: font-size, padding --- how to control this?

### ISSUE THREAD

**Issue by geoidesic** [illright/attractions#262]
How do I control:
1. the padding on a button
2. the font-size on a button

**Comment by illright** [comment]
You cannot control these parameters directly, but there are several ways to influence them:
* The padding uses `em`, so as the font size increases, so will the padding
* The font size uses `rem`, so the buttons will have the font size that is identical to the general font size of the page
* You may change the styling of individual buttons by writing styles that go inside the buttons:
```svelte
<div class="test">
  <Button>hello</Button>
</div>

<style>
  .test :global .btn {
    /* change whatever you see fit, this style is still scoped to this component */
  }
</style> 
```

**Comment by geoidesic** [comment]
Just realised I didn't fully understand the implications there... I think button padding should definitely be a global var that get's used by the Button element then. You definitely don't want to prevent designers from controlling padding on buttons globally... that's enough to cause a hissy fit.

**Comment by illright** [comment]
I suggest we continue this discussion in #265, to keep it all in one place
