### ISSUE TITLE
How can I use hex colours?

### ISSUE THREAD

**Issue by geoidesic** [illright/attractions#263]
// theme.scss
```
@forward '~attractions/_variables' with (
  $main: "#ff4002",
  $font: "'Open Sans', sans-serif",
  $button-radius: 4px
);
$something-else: red;
```
`Error: $color2: "#ff4002" is not a color.`

**Comment by illright** [comment]
In Sass, colors do not require quotation, as most values, so you may use a hex color simply by removing the quotes around the value. The reason there are quotes around the value of `$font` is because there's a comma inside.
