### ISSUE TITLE
How do I control the style of a Dialog?

### ISSUE THREAD

**Issue by geoidesic** [illright/attractions#264]
```
<Dialog
  title="Are you sure you want to exit?"
  closeCallback={() => console.log('Closing the dialog...')}
  danger
>
  <p>You have not saved your changes yet.</p>
  <p>If you exit without saving, changes will be lost.</p>
  <p>Are you sure you want to exit?</p>
  <Button>yes, exit</Button>
</Dialog>
<style>
.dialog{
   position: absolute;
   top: 100px;
}
</style>
```

The styling here doesn't work.

I can add a class to the Dialog like so:
```
<Dialog
  class="brown"
>
```

But I can't seem to write a selector that will affect that element. I've tried everything I can think of.

**Comment by illright** [comment]
I've shown a way in #262 to reach other components with your styles: the `:global()` modifier. This doesn't create leakage as long as it has at least one local part of the selector.

In your case, if `Dialog` is the only element of the markup of the component, you won't be able to write a scoped style (though you can still write a global style, if you're fine with that). You may get around this limitation by wrapping this `Dialog` in an element or put a preceding element and use that as your local part of the selector:

```svelte
<div class="test" />
<Dialog />

<style>
  .test + :global .dialog {
    /* perfectly scoped yet still reaching the Dialog component */
  }
</style>
```

**Comment by illright** [comment]
The reason why all components accept a `class` prop is to allow applying global styles to components (such as those coming from external CSS files) or to specify which `Dialog` do you want exactly:

```css
.test :global .brown {}
```
