### ISSUE TITLE
DatePicker/TimePicker miss inputClass

### ISSUE THREAD

**Issue by jcschmidig** [illright/attractions#269]
It would be nice to have the inputClass also for Date/TimePicker. This is a very convenient way to instruct and style the component.

**Comment by illright** [comment]
What DOM element in particular would you like to style with `inputClass`? The thing is, `DatePicker` doesn't even have an `<input>` internally, it only borrows it from `TextInput`. Do you want to style the `<input>` element of these `TextInput`s?

**Comment by jcschmidig** [comment]
As the name says, it's the input class of the respective TextField element. It's not only for styling but also for processing within the form where it's included. Additionally it would be nice to propagate the $$restprops to the TextField too.
Great job by the way. I really like your work.

**Comment by illright** [comment]
Why did you close this issue? It does seem like a nice addition
