### ISSUE TITLE
Best practice for having multiple themes

### ISSUE THREAD

**Issue by OG84** [illright/attractions#271]
Is there a best practice for having multiple themes?

E.g. a light and dark theme which can be toggled at runtime?

I had no problem in setting up one theme with sveltekit. Also overriding variables using @forward was fine.
But I could not find a solution to get it working with multiple theme files, because overriding with @forward can only be defined in one file because it's at compile time.

But for having multiple themes there must be some other dynamic approach 🤔 
Of course I could globally overwrite every attraction component class, but would be nice to be able to only override the variables dynamically.

**Comment by illright** [comment]
I must confess that this issue wasn't really considered, hence there are no best practices that we may offer. In fact, considering this right now, I don't even know how I would implement this.

All I know, if this feature is to be implemented nicely, it would have to be an overhaul in the styles of Attractions itself, I don't think much elegant solutions can be done from outside. I'm thinking something like a Sass function for selectors that can be overriden to turn a regular selector into a dark theme selector (that could prepend `:global(body.dark) ` by default) and a special set of variables for the dark theme colors, and make it opt-in somehow. But I can't promise to get working on that any time soon, so if you're interested in a major contribution like this, I'd gladly provide guidance :)

**Comment by OG84** [comment]
I saw this other issue where one approach was using css variables as an input to the scss variables.
But i think then we can not use the nice sass helpers like `color.adjust(...)` etc. anymore.
ok let's see I will also think about it and maybe look how other frameworks tackle this.
thx 🚀
