### ISSUE TITLE
[Feature request] Tooltip component

### ISSUE THREAD

**Issue by edazpotato** [illright/attractions#273]
It would be great to have a tooltip component that matches the design of this library.

Example of how it could be used:
```svelte
<script>
  import { Button, Tooltip } from "attractions";
</script>

<Tooltip position="top">
  <Button>Hello, world!</Button>
</Tooltip>
```

I would be happy to have a go at implementing it myself, but after poking around the code little bit I was unable to work out how to preview and document components.

**Comment by aabounegm** [comment]
There is already the [`Popover`](https://illright.github.io/attractions/docs/components/popover) component that seems to do precisely what you are describing. Does it suit your needs or are you looking for something different?
And about documentation, don't worry. Any small contribution is welcome and we can always help 😁
