### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kapilbhavsar** [illright/attractions#274]
Can you share the roadmap of future components that you are planning to come up with, because a lot many components are missing. e.g. button groups, tree view etc.

**Comment by illright** [comment]
There isn't a roadmap for now, we, the maintainers, currently don't have much time to work on new functionality for this library.

I'm thinking that the first steps that we'd take would be reworking the documentation and addressing the major API design flaws such as the lack of flexibility for buttons (discussion in #265) and the inability to adapt the theme to dark mode (discussion in #271). Then we might proceed to adding new components.

All that said, we greatly welcome contributions. If there's a particular component that you feel is missing, I encourage you to create a thread in GitHub Discussions in this repository, where you could propose an API (props, Sass variables, slots, etc.) and maybe a design vision (even a mockup on a napkin will do). Then you, us, or someone else could start working on this component and have it added to the library.

**Comment by illright** [comment]
We have a roadmap in form of a project board now: https://github.com/illright/attractions/projects/1
I'll emphasize that we are open to suggestions for new components in the Discussions of this repository. Feel free to post there.

Closing this issue.
