### ISSUE TITLE
Implement automatic positioning of the `Dropdown`

### ISSUE THREAD

**Issue by illright** [illright/attractions#294]
Implement automatic positioning for the `Dropdown` (and hence the `DatePicker` and `TimePicker`).

**Comment by Th1nkK1D** [comment]
Hey, could you clarify this issue a bit more? I might be able to help.

**Comment by illright** [comment]
Hi, sure. What we're looking for is an efficient way to position the dropdown in a way that it doesn't open off-screen. This could be a setting with a prop like `autopositioned` or something.

**Comment by aabounegm** [comment]
I also agree with the logic, but not with the prop. I think that autopositioning should be the default way if the other props (`right` and `top`) are not given, no extra props needed.

**Comment by aabounegm** [comment]
Changing the default behavior when not passing any props from bottom-left to auto doesn't feel all that breaking to me. Actually, autoposition is what I would generally expect from any Dropdown component by default. I would guess that whoever didn't use `right` or `top` already is satisfied with bottom-left alignment, which would also be the default of the auto-positioning if there is enough space (and we can safely assume that there is, because otherwise the `right` or `top` props would have been used already).

**Comment by Th1nkK1D** [comment]
> I see what you mean. Indeed, that's a problem, and changing from CSS to conditional rendering is surely a breaking change. I have some preliminary ideas:
> 
> 1. Since `DropdownShell` is essentially the controller, we could implement the positioning logic there, by dynamically locating the `.dropdown` element inside. However, it feels fragile to me, especially in the case of nested dropdowns (however barbaric that is)
> 2. Alternatively, we could use context from `DropdownShell` to pass the information about the `open` state down to `Dropdown` and go from there
> 
> What do you think?

Context sound like an interesting idea. I will look into that idea.

> This might be a dumb question, but couldn't this be fixed by switching from `display: none;` to `visibility: hidden;` so that the element has size and position? The dropdown is absolutely positioned, so it shouldn't affect the normal document flow.

Yes, the drop-down size is static. But we need to consider the position of the drop-down on the viewport as well. If we recheck it every time the viewport scroll is changed (onScroll event), I think it will be overkill. So calculating it when the dropdown is open sounds more efficient to me.

**Comment by Th1nkK1D** [comment]
I created the PR #318. The solution is a bit messy to me, please let me know what do you think.
