### ISSUE TITLE
Using TextField for password inputs

### ISSUE THREAD

**Issue by pietz** [illright/attractions#299]
I currently use `TextField`s within `FormField`s for a Login component. How would I set up the password censoring behavior similar to `type=password` in HTML `input` fields? What else would I need to do so the browser will do its autofill thing?

**Comment by illright** [comment]
Just give the `TextField` a `type="password"` prop like you would to a regular `<input>`, that's all there is

**Comment by illright** [comment]
I hope the question was resolved. You're welcome to GitHub discussions if you find yourself in need of further assistance. I'm closing this issue.
