### ISSUE TITLE
Documentation offline

### ISSUE THREAD

**Issue by Codex-** [illright/attractions#303]
It appears with the latest release that the documentation is now offline: https://illright.github.io/attractions/

![image](https://user-images.githubusercontent.com/8297838/133017548-0e029661-fc23-4bb5-935c-4485d2e73c3c.png)

Just an FYI :)

**Comment by illright** [comment]
Hi, thanks for the report! We rolled out a release yesterday and it failed, we will fix this issue shortly.

**Comment by Codex-** [comment]
looks like it's working now, cheers.
