### ISSUE TITLE
Migrate to SvelteKit

### ISSUE THREAD

**Issue by benmccann** [illright/attractions#311]
Sapper is no longer actively developed and SvelteKit is a much better experience

Migration guide: https://kit.svelte.dev/migrating

**Comment by illright** [comment]
When I mentioned jank a few days ago, I was recalling from memory. Today I went ahead and tried it again. 

The Vite server starts almost instantly, which is great, but then the first request to `localhost` takes around 10-15 seconds to complete. If I then hit Reload, the reloads will also take a long time, sometimes even longer than the initial load. Sometimes during reloads, I get random 500 errors, sometimes only in the tab title, sometimes they break through to the screen. The error message is `TypeError: Failed to fetch dynamically imported module` with no helpful logs (not even a 500 report) in the Node console. Sometimes Chrome reports the page to be unresponsive. The "loading page" spinner in the tab gets visibly janky, my laptop fans engage as if the browser is struggling to load the page. Hitting the "stop loading" cross icon doesn't stop the spinner from spinning, it's as if the tab is now so broken that it doesn't respond to Chrome anymore.

This amounts for a rather unpleasant development experience. I think we should stay with Sapper until this performance issue gets resolved. I'm happy to aid in investigating that issue.

**Comment by illright** [comment]
Uh-huh, I updated and now the duplication is gone. The performance issue still persists though.

What was black for me then is still black now. Moreover, I've noticed that tracebacks are also printed in this color:
![traceback](https://user-images.githubusercontent.com/15035286/137374513-cef8e7df-c360-4049-a56c-0d90c76a6022.png)

Maybe we could use a theme-independent color here?

**Comment by benmccann** [comment]
>  Sometimes during reloads, I get random 500 errors, sometimes only in the tab title, sometimes they break through to the screen. 

This seems to be due to broken links. It appears we don't give very good error messages when trying to prefetch a page that doesn't exist. If you're able to fix all the links first then I can take another look at any remaining jank or performance issues

E.g. if you're on http://localhost:3000/docs/components/button and click "migration guide" you will be taken to http://localhost:3000/docs/components/docs/migration-guide instead of http://localhost:3000/docs/migration-guide.

> Uh-huh, I updated and now the duplication is gone

Did you just do that locally? I don't see the changes appearing

> What was black for me then is still black now.

We print it in `gray`: https://github.com/sveltejs/kit/blob/7fab7f67a4643715586693cf01fd4d43f54671d0/packages/kit/src/cli.js#L238

If your terminal theme is showing gray as black, it seems more to me like the bug would be in your terminal theme. I'm hesitant to try to work around that in SvelteKit because there's an infinite number of terminal themes out there and if we fix it for one then we'll probably break it for another. I haven't seen anyone else hit this issue before

**Comment by aabounegm** [comment]
I also can't reproduce any errors. I thought I'd give it a shot, since my OS is quite different than @illright's (I use Windows 10, he uses Linux and I forgot which distro 😁). To make it work, I first had to replace any usages of the custom resolve function from [resolve.js](https://github.com/illright/attractions/blob/28e7d6a431cfdf8c557499d50491c78386b8280c/docs/resolve.js) with the one built-in in Node, while also removing the `import.meta.url` part. Then it worked without further modifications.

About the 2 errors, it is not that the file path has not been updated, but rather they were missed in [the commit where all the styles where inlined](https://github.com/illright/attractions/pull/312/commits/6eb0bd015dc3a4ee1fd25dd83aa6476381f8b4c0). In fact, there are 5 of them and I believe they are a problem of copy-pasting files, forgetting to remove the style import, the styles not applying due to different selectors, and not getting any errors earlier due to the files existing. None of that is SvelteKit's problem, but I'm just writing my diagnosis of the issue so that we (@illright) can fix them.

As for the issues described above, everything is working very smoothly. Yes, the initial page load is relatively slow, but I understand that's due to how Vite works, with all the compiling on demand. After the initial load, I get no more jittering. Also, all the colors look good on my terminal with a white background.

<details>
<summary>
System info
</summary>

```
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 6.24 GB / 15.84 GB
Binaries:
    Node: 16.9.1 - C:\Program Files\nodejs\node.EXE
    npm: 7.21.1 - C:\Program Files\nodejs\npm.CMD
Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (94.0.992.47)
    Internet Explorer: 11.0.19041.1202
npmPackages:
    svelte: ^3.43.2 => 3.43.2
```

</details>

**Comment by illright** [comment]
Thank you for a thorough investigation :)

I believe it was once a best practice for Sapper to install Svelte packages to development dependencies for SSR. I have a lot of questions:
1. Is it still the case? 
2. Is that why `svelte-feather-icons` are causing trouble? 
3. Do we as library maintainers have to do anything about the way we ship Attractions to make sure it's snappy for our users?
4. If bundled versions of libraries are used, does that mean that our customisation scheme of Attractions will no longer work in SvelteKit?

**Comment by illright** [comment]
I've implemented a preprocessor that does rudimentary import re-routing and it seems to work well in my case. I've read the thread you've linked and saw that you were discussing a similar thing with the maintainers of Carbon Components. Perhaps we should polish it up and publish it, maybe even under the hood of the Svelte organization. What do you think?

As a future improvement, we could make this automatic – follow the Node resolution algorithm and rewrite imports without specifying the rule.

**Comment by benmccann** [comment]
Yes, I proposed making a generic library for it in https://github.com/carbon-design-system/carbon-preprocess-svelte/issues/20. Though there's also been another proposed solution that we may want to consider: https://github.com/sveltejs/kit/issues/2612#issuecomment-944942192

It seems like the PR to convert to SvelteKit is getting pretty close now! Is there anything else you want to fix before merging it?

**Comment by benmccann** [comment]
Since `1.0.0-next.185`, you can set [experimental.prebundleSvelteLibraries: true](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md#prebundlesveltelibraries) in `svelte.config.js` to test out the new prebundling handling to solve the speed issue without the need for a preprocessor. `1.0.0-next.185` also allows you to use Vite's `define` and environment variables in `.svelte` templates

**Comment by benmccann** [comment]
> Sapper used to have a placeholder %sapper.base%, SvelteKit doesn't seem to have it. How can we work around this?

You could file a feature request in the SvelteKit repo and in the meantime you could create a `src/hooks.js` file that uses a `handle` method to search and replace those strings to include the base path

**Comment by benmccann** [comment]
https://github.com/sveltejs/kit/issues/2697 has been resolved, so hopefully you can continue the migration now!

**Comment by illright** [comment]
@benmccann We've proceeded further with the migration, however, now, a rather puzzling error appears upon trying to export the site:
```
> Using @sveltejs/adapter-static
> 404 /docs/components (linked from /docs/components/autocomplete-option)
    at file:///home/illright/work/attractions/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.230_sass@1.48.0+svelte@3.46.2/node_modules/@sveltejs/kit/dist/chunks/index5.js:314:11
    at visit (file:///home/illright/work/attractions/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.230_sass@1.48.0+svelte@3.46.2/node_modules/@sveltejs/kit/dist/chunks/index5.js:473:5)
```

To reproduce this, run `pnpm docs:build` in the root directory of the repository.

The error suggests that we have a link to `/docs/components` somewhere in `/docs/components/autocomplete-option`, however, there is none. I've checked the source code, the "View Source" view in dev mode, the produced files in `.svelte-kit` and `build` directories, none of them contain a link to `/docs/components`, only to `/docs/components/<whatever>`, which exist in the routes. I don't quite understand where this link comes from. Any ideas?

**Comment by benmccann** [comment]
This is a regression in Kit. I sent a fix (https://github.com/sveltejs/kit/pull/3367). In the meantime, you can make it work by temporarily downgrading to `1.0.0-next.220`

**Comment by benmccann** [comment]
The SvelteKit fix has been merged and release, so it should work now with the latest version of SvelteKit

**Comment by benmccann** [comment]
@illright just checking in on this since it seemed like you were almost done with it. is there anything you're currently stuck on that I might be able to lend some advice about?

**Comment by illright** [comment]
Nothing particular that we're stuck with, we're not making much progress due to a lack of motivation :) I appreciate you checking in though, I might come back to this for another burst some time soon.

**Comment by aabounegm** [comment]
@benmccann I have restarted the work in the new Pull Request linked above. Please take a look and tell me what you think. The failing pipeline for now is the linting one, which is expected when moving from JavaScript to TypeScript and uncovering a lot of problems, but there is one issue I could use help with: `svelte-check` (and the VS Code extension as well) reports this problem: `Cannot find module '$app/paths' or its corresponding type declarations.` (actually for any `$app/...` import). Any idea how to fix that?
