### ISSUE TITLE
Add the possibility to customize some words in Attractions

### ISSUE THREAD

**Issue by Bluzzi** [illright/attractions#315]
Hello, in the FormField (and probably in other places), there are words like "Required", "Optional". The problem is that this is not suitable for a site in French for example.

It would be cool to be able to change these words !

**Comment by illright** [comment]
Hi! You're right, this should definitely be added. I wish Attractions had a comprehensive localization system, but until then we can get away by just defining slots `required-message and `optional-message`.

You're welcome to contribute by implementing this feature. Would you like that or should we implement it?

**Comment by Bluzzi** [comment]
Hello, is this package still available? If I take care of this issue now, can someone review my PR and publish a new version of this package on NPM?

**Comment by aabounegm** [comment]
@Bluzzi Yes. We have been inactive (in terms of development) recently mainly because both of us (the maintainers) were busy with our university work, but any contribution is still welcome and we try to respond promptly.

**Comment by Bluzzi** [comment]
Great! I'll take care of that in the next few days
