### ISSUE TITLE
Question: Setting different colors to buttons?

### ISSUE THREAD

**Issue by Beiri22** [illright/attractions#324]
Hi there,

As I understand, you can change colors and many other settings globally as a theme. But is it possible to change colors on per-component base? Example: Two buttons next to each other: One reddish for cancel, one greenish for continue.

Thank you.

**Comment by illright** [comment]
Hi! Afraid not. There is a `danger` prop on Buttons that makes them red, but no way to make them green.

**Comment by Beiri22** [comment]
So there is no way to override $main variable for a specific component instance only?

**Comment by illright** [comment]
Unfortunately, no. You could still change the background color of the button to whatever you want, but you'll have to write your own CSS for that.

**Comment by Beiri22** [comment]
I see. I think the library could benefit from such form of local customization, not only for buttons; maybe also for Badge, Card, Chip, ... ;-)

**Comment by illright** [comment]
That is certainly true. In the future we will use CSS variables to allow for such customizations.

**Comment by Beiri22** [comment]
That is nice to hear. I'm looking forward to trying this. Thank you!

**Comment by illright** [comment]
Seeing as there's no more open questions left, I'll close this issue
