### ISSUE TITLE
Autocomplete: Property 'getOptions' does not exist on type 'IntrinsicAttributes & AutocompleteProps'

### ISSUE THREAD

**Issue by ThomasOrlita** [illright/attractions#325]
I'm using the Autocomplete element, but TypeScript is complaining that the `getOptions` property doesn't exist.

![image](https://user-images.githubusercontent.com/17808846/142737763-70d8b3d4-fe38-4279-97c5-401795876b6d.png)

Attractions 3.5.0
Svelte 3.44.2
TypeScript 4.5.2

**Comment by aabounegm** [comment]
Thank you for filing this issue. The problem was due to updating to a [sveld](https://github.com/carbon-design-system/sveld) without checking the changelog first 😅, which caused a type import (the one being extended by `Autocomplete`) to be invalid. A pull request fixing this issue is in progress.

**Comment by aabounegm** [comment]
The patch has been released with version `3.5.1`. Please verify that the issue is indeed fixed.

**Comment by ThomasOrlita** [comment]
Thanks for the quick update!

Now it however lights up with a different error:
```
Type '(text: any) => AsyncGenerator<({ name: any; details: string; } | { name: string; details?: undefined; })[], void, unknown>' is not assignable to type 'OptionsGetter'.
  Property '[Symbol.iterator]' is missing in type 'AsyncGenerator<({ name: any; details: string; } | { name: string; details?: undefined; })[], void, unknown>' but required in type 'Generator<Promise<Option[]>, never, never>'.
```

This is the code (from the demo):
```html
<script lang="ts">
  import { Autocomplete } from 'attractions';

  async function* getOptions(text) {
    yield [{ name: text, details: 'Optional' }, { name: `it highlights the match: ${text}` }];
  }
</script>

<Autocomplete getOptions={getOptions} />
```

**Comment by aabounegm** [comment]
Hmm. I'm not so familiar with generator functions' types, but do you think
```ts
type OptionsGetter = (q: string) => AsyncGenerator<Option[], void, void>;
```
would be more appropriate?

**Comment by ThomasOrlita** [comment]
> Hmm. I'm not so familiar with generator functions' types, but do you think
> 
> ```ts
> type OptionsGetter = (q: string) => AsyncGenerator<Option[], void, void>;
> ```
> 
> would be more appropriate?

I think this type should work. 👍

**Comment by aabounegm** [comment]
Does release `v3.5.2` fix the issue?

**Comment by ThomasOrlita** [comment]
Yes, it's fixed now. Thank you!
