### ISSUE TITLE
Table style customizations

### ISSUE THREAD

**Issue by techpet** [illright/attractions#337]
What is the best way to change the styles of the table  internal elements? For example change the `thead` background-color or remove the border from `td`?

I've tried overriding them with:
```
<style type="scss">
table {
	td {
		border:none;
	}
}
</style>
```
and
```
<style type="scss">
.my-table {
	td {
		border:none;
	}
}
</style>

<Table class="my-table" ... />
```

but neither works.

**Comment by illright** [comment]
Due to the way Svelte scopes its styles, you have to specifically opt out of scoping for your styles to reach the components of Attractions. Try the following:

```diff
<style type="scss">
-.my-table {
+.my-table :global {
	td {
		border:none;
	}
}
</style>

<Table class="my-table" ... />
```

**Comment by techpet** [comment]
Unfortunately that doesn't work either in my component...

**Comment by techpet** [comment]
If I place the style code inside the global.scss instead of inline into my component it works though. Any ideas?

**Comment by techpet** [comment]
Perfect! It works this way, thank you very much!
