### ISSUE TITLE
How to use custom fonts for e.g. FormFields?

### ISSUE THREAD

**Issue by zPhoeniqz** [illright/attractions#341]
How do I do that?<br>
Fonts I imported from Google fonts don't work with the attractions components if I forward the _variables file with e.g. <br><code>$font: "'Varela Round', sans-serif"</code><br>
It seems as if only default fonts work.

**Comment by illright** [comment]
I need to see how you link fonts to the application to investigate the issue. Could you please provide a short reproduction of the issue, perhaps in StackBlitz or a repository?

**Comment by zPhoeniqz** [comment]
I thought I could just make an <code>@import</code> statement to my font in the theme.scss file and then <code>@forward</code> the <code>_variables</code> with <code>$font</code> set to my imported font. But three days later and maybe a tiny bit smarter I think that the reason you can't do that is something related to SCSS. I think SCSS doesn't forward the imported stuff to another file even if it's needed there. It would still be nice to have an optiion of setting a custom font though, but it's understandable that there isn't one (yet).

<br>
theme.scss:
<pre>
<code>
@import url('https://fonts.googleapis.com/css2?family=Varela+Round&display=swap');

@forward '~attractions/_variables' with (
    $main: #1e3799,
    $font: "'Varela Round', sans-serif"
);
</code>
</pre>
<br>
The only kind of solution I found is doing following in the <code>app.html</code>:
<pre>
<code>
<style>
	@import url('https://fonts.googleapis.com/css2?family=Varela+Round&display=swap');

	* {
		font-family: 'Varela Round', sans-serif !important;
	}
</style>
</code>
</pre>
But the problem with this one is that it doesn't set the font explicitly for the attractions components like <code>$font</code> would.

**Comment by illright** [comment]
The trick here is to link the font in the HTML using a `<link>` tag ([example](https://github.com/Innopoints/frontend/blob/main/src/template.html#L20-L23)) and then using its name in the `$font` variable ([example](https://github.com/Innopoints/frontend/blob/main/static/css/_attractions-theme.scss#L4)).

**Comment by aabounegm** [comment]
Since there haven't been any replies on this issue for 2 weeks, I'll assume the issue is resolved
