### ISSUE TITLE
Is illright.me down? (Attractions main documentation source)

### ISSUE THREAD

**Issue by divStar** [illright/attractions#357]
Hey there,

I thought I'd ask (I hope I didn't miss anything): is the website down and is there perhaps a mirror or something? Or something I can help with?

I like the framework so far, even though I only used it for a little bit, and it'd be sad to see it go :(.

**Comment by illright** [comment]
Sorry, `illright.me` was never intended to be the domain for the docs website. It's my fault, I fixed it now. The website is live at https://illright.github.io/attractions, the usual place :)

Thanks for the report!

**Comment by divStar** [comment]
Thank you very much!
