### ISSUE TITLE
CSS media breakpoints support?

### ISSUE THREAD

**Issue by divStar** [illright/attractions#358]
Hi there,

I would like to know if there is any kind of CSS media breakpoints support.

My current case: I have chips for a particular view selection and I would like to hide the text labels if the screen width becomes smaller than a certain amount of pixels.

<img width="790" alt="grafik" src="https://user-images.githubusercontent.com/138585/189667952-5a2a30e8-8167-4a7b-985d-3c1232fcc0e4.png">
 =>

<img width="536" alt="grafik" src="https://user-images.githubusercontent.com/138585/189668115-de128519-96b0-4bd3-84eb-0d2718cf6493.png">

In the latter screenshot I'd like to hide the text in the chip.

Should I code it by my own? I know e.g. Tailwind CSS supports this and from what I remember there are other frameworks in general, which are "media breakpoints"-aware.

**Comment by illright** [comment]
Yeah, you'll have to code these yourself. Attractions does ship with some media queries to adapt the components to screen sizes, but custom adaptation logic will have to be coded in manually
