### ISSUE TITLE
There are links to broken doc site pages

### ISSUE THREAD

**Issue by mrme44** [illright/attractions#363]
If you go to [https://illright.github.io/attractions/docs/](https://illright.github.io/attractions/docs/) and click on the components dropdown, nothing happens. Instead you have to go to [https://illright.github.io/attractions//docs/](https://illright.github.io/attractions//docs/). Notice the extra slash. There are links on [Github](https://github.com/illright/attractions) that link to the docs page with one slash, which is how I ended up discovering this problem.

**Comment by aabounegm** [comment]
Hmm, this is an interesting bug. I don't quite understand why that happens, but I assume Sapper is part of the problem because I didn't face this when migrating to SvelteKit (which will hopefully be merged soon).
