### ISSUE TITLE
Vite

### ISSUE THREAD

**Issue by NelminDev** [illright/attractions#365]
How can I install attractions with vite?

**Comment by illright** [comment]
Hi! I'm not sure how to answer that. Did you try the installation instructions on the website? What problems have you encountered?

**Comment by NelminDev** [comment]
There is no tutorial for Vite on the website, only for Webpack and Rollup

**Comment by illright** [comment]
True. The most important part is to install svelte-preprocess, after which you can follow the Rollup installation. I believe svelte-preprocess is installed automatically by create-svelte if you select something that needs it, like typescript

**Comment by NelminDev** [comment]
So I only need to add attractions, sass and postcss?

**Comment by illright** [comment]
Yes

**Comment by NelminDev** [comment]
PnPm say that I need to install svelte-preprocess
