### ISSUE TITLE
DatePicker shows different month than the selected on specific dates

### ISSUE THREAD

**Issue by OfficialFreak** [illright/attractions#368]
I've just encountered a bug when opening the DatePicker on the 31st of May. The Calendar opens the May page but when switching months, it acts as if June was selected. E.g. clicking "next month" would open the page for July and when clicking "previous month" it would stay on the May page. This would only occur once on page load. This bug is not present on the 1st of June although I believe there might be other edge-case dates that produce similar errors.

**Comment by illright** [comment]
Hi! Attractions is currently inactively maintained, so it is unlikely that we will get around to address this issue. If you'd like to try your hand at it though, you're more than welcome to! We'd love to get a PR to fix this

**Comment by shayneoneill** [comment]
Could you please put up something on your front page about it not being maintained. I've just spent a day trying to get this thing to work to no avail, and it would have saved me a lot of time... Cheers.

**Comment by aabounegm** [comment]
@shayneoneill It is mentioned in the first badge in the README that the repo is "inactively maintained" (meaning we are not currently pushing it forward, but welcome contributions)
